export const defaultSettings = {
  prepDuration: 5,
  workDuration: 15,
  restDuration: 15,
  workouts: [
    'Soga salto',
    '6 x 6',
    '6 x 6 con cambio',
    'Medio Burpee',
    'Escuadra con MB',
    'Aperturas veloces',
    'Garrote a estocada',
    '6 x 6',
    'Plancha con bastón vertical',
    '6 x 6',
    'Varilla',
    'Medio Burpee',
    'Bicicleta',
    '6 x 6',
    'Medio Burpee',
    '6 x 6',
    'Levantada con bastón y desplazamiento',
    'Push up',
  ],
}
