export const defaultSettings = {
  prepDuration: 10,
  workDuration: 15,
  restDuration: 15,
  labelPrep: 'Staring session...',
  labelRest: 'Resting...',
  workouts: [
    'Saltar la soga',
    '6 x 6',
    '6 x 6 con cambio',
    'Medio Burpee',
    'Aperturas veloces',
    'Garrote a estocada',
    '6 x 6',
    'Plancha con bastón vertical',
    '6 x 6',
    'Varilla',
    'Medio Burpee',
    'Bicicleta',
    '6 x 6',
    'Burpee combinado',
    '6 x 6',
    'Medio Burpee',
    'Push up',
  ],
}
